// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHf5V86rAQjeiqhf2ods1nFWgbRmFACXU',
    appId: '1:887777635287:web:60b6f31f0b1c69179bb992',
    messagingSenderId: '887777635287',
    projectId: 'secbpcpsdemo',
    authDomain: 'secbpcpsdemo.firebaseapp.com',
    storageBucket: 'secbpcpsdemo.firebasestorage.app',
    measurementId: 'G-GSNJRDFSRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8it0OlzVezVj_JIlwaC3JHcCkrYLAFA',
    appId: '1:887777635287:android:964bcb6472fa3ef99bb992',
    messagingSenderId: '887777635287',
    projectId: 'secbpcpsdemo',
    storageBucket: 'secbpcpsdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsclO4Lt2WMBYuB0JZpcE7G_l0bhqEGGs',
    appId: '1:887777635287:ios:9c28787e2686bde69bb992',
    messagingSenderId: '887777635287',
    projectId: 'secbpcpsdemo',
    storageBucket: 'secbpcpsdemo.firebasestorage.app',
    iosBundleId: 'com.pcps.demopcps',
  );

}